services:
  app:
    image: node:lts-alpine
    working_dir: /app
    command:
      - node
      - ace
      - serve
      - --watch
      - --no-assets
    ports:
      - 3333:3333
    environment:
      SILENT_ENV: true
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: nMzmnNho0MzOrWew0DFywB3Zn07wqDNj
      DRIVE_DISK: local
      SESSION_DRIVER: cookie
      CACHE_VIEWS: false
    volumes:
      - ./src:/app:rw
    depends_on:
      - encore
  ace:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - node
      - ace
    volumes:
      - ./src:/app:rw
  yarn:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - yarn
    volumes:
      - ./src:/app:rw
  encore:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - yarn
      - encore
      - dev
      - --watch
    volumes:
      - ./src:/app:rw
