services:
  app:
    image: node:lts-alpine
    working_dir: /app
    command:
      - yarn
      - run
      - dev
    ports:
      - 3333:3333
      - 8080:8080
    environment:
      SILENT_ENV: true
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: nMzmnNho0MzOrWew0DFywB3Zn07wqDNj
      DRIVE_DISK: local
      SESSION_DRIVER: cookie
      CACHE_VIEWS: false
    volumes:
      - ./src:/app:rw
  ace:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - node
      - ace
    volumes:
      - ./src:/app:rw
  yarn:
    image: node:lts-alpine
    working_dir: /app
    entrypoint:
      - yarn
    volumes:
      - ./src:/app:rw
